# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that infotm device is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)
$(call inherit-product-if-exists, device/infotm/imapx800/InfotmMedia/release.mk)

# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.


SRC_HEADERS += \
	$(TOPDIR)device/infotm/imapx800/include


# These are the hardware-specific configuration files
PRODUCT_COPY_FILES += \
	device/infotm/imapx800/etc/mmc.ixl:system/etc/mmc.ixl \
	device/infotm/imapx800/etc/nand.ixl:system/etc/nand.ixl \
	device/infotm/imapx800/etc/netpolicy.xml:system/etc/netpolicy.xml\
	device/infotm/imapx800/etc/alsa_dmic.conf:system/etc/alsa_dmic.conf \
	device/infotm/imapx800/etc/asound_dmic.conf:system/etc/asound_dmic.conf \
	device/infotm/imapx800/etc/nand_without_logo.ixl:system/etc/nand_without_logo.ixl \
	device/infotm/imapx800/etc/burninit.isi:system/etc/burninit.isi \
	device/infotm/imapx800/egl/egl.cfg:system/lib/egl/egl.cfg

#audio_policy.conf

PRODUCT_COPY_FILES += \
	device/infotm/imapx800/etc/audio_policy.conf:system/etc/audio_policy.conf
#recovery
PRODUCT_COPY_FILES += \
	device/infotm/imapx800/etc/recovery.fstab:root/recovery.fstab \

# Init files
#PRODUCT_COPY_FILES += \
	device/infotm/imapx800/init.rc:root/init.rc \

#gps conf
PRODUCT_COPY_FILES += \
	device/infotm/imapx800/etc/firmware/rt2870.bin:system/etc/firmware/rt2870.bin \
	device/infotm/imapx800/etc/Wireless/RT2870STA/RT2870STA.dat:system/etc/Wireless/RT2870STA/RT2870STA.dat \
	device/infotm/imapx800/etc/Wireless/MT7601U/RT2870STA.dat:system/etc/Wireless/MT7601U/RT2870STA.dat \
	device/infotm/imapx800/etc/Wireless/MT7601U/MT7601EEPROM.bin:system/etc/Wireless/MT7601U/MT7601EEPROM.bin \
	device/infotm/imapx800/etc/firmware/gps/aiding.bin:system/etc/firmware/gps/aiding.bin \
	device/infotm/imapx800/etc/ppp/ip-down:system/etc/ppp/ip-down \
	device/infotm/imapx800/etc/ppp/ip-up:system/etc/ppp/ip-up \
	device/infotm/imapx800/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
	device/infotm/imapx800/etc/nvram/APCFG/APRDEB/WIFI:system/etc/nvram/APCFG/APRDEB/WIFI \
	device/infotm/imapx800/etc/nvram/APCFG/APRDEB/WIFI_CUSTOM:system/etc/nvram/APCFG/APRDEB/WIFI_CUSTOM \
	device/infotm/imapx800/etc/ppp/chap-secrets:system/etc/ppp/chap-secrets

#usbdongle
PRODUCT_COPY_FILES += \
    device/infotm/imapx800/bin/chat:system/bin/chat \
	device/infotm/imapx800/bin/usbdongle:system/bin/usbdongle \
	device/infotm/imapx800/bin/usbdongled:system/bin/usbdongled \
    device/infotm/imapx800/lib/libusb.so:system/lib/libusb.so \
    device/infotm/imapx800/lib/libusbdongle.so:system/lib/libusbdongle.so \
	device/infotm/imapx800/etc/apns-conf.xml:system/etc/apns-conf.xml \
    device/infotm/imapx800/default.prop:system/default.prop 

#moudles
PRODUCT_COPY_FILES += \
    device/infotm/imapx800/modules/mali.ko:system/lib/modules/mali.ko \
    device/infotm/imapx800/modules/ump.ko:system/lib/modules/ump.ko \
    device/infotm/imapx800/modules/8192cu.ko:system/lib/modules/8192cu.ko \
    device/infotm/imapx800/modules/8192cu_mp.ko:system/lib/modules/8192cu_mp.ko \
    device/infotm/imapx800/modules/RTL8188EUS.ko:system/lib/modules/RTL8188EUS.ko \
    device/infotm/imapx800/modules/RTL8188EUS_mp.ko:system/lib/modules/RTL8188EUS_mp.ko \
    device/infotm/imapx800/modules/rt5370v2_sta.ko:system/lib/modules/rt5370v2_sta.ko \
    device/infotm/imapx800/modules/rt5370sta.ko:system/lib/modules/rt5370sta.ko \
    device/infotm/imapx800/modules/wlan.ko:system/lib/modules/wlan.ko \
    device/infotm/imapx800/modules/mt7601Usta.ko:system/lib/modules/mt7601Usta.ko \
    device/infotm/imapx800/modules/ubi.ko:recovery/root/sbin/modules/ubi.ko \
    device/infotm/imapx800/modules/ubi.ko:root/sbin/modules/ubi.ko \
    device/infotm/imapx800/modules/ubifs.ko:recovery/root/sbin/modules/ubifs.ko \
    device/infotm/imapx800/modules/ubifs.ko:root/sbin/modules/ubifs.ko 	\
    device/infotm/imapx800/modules/uftl.ko:recovery/root/sbin/modules/uftl.ko \
    device/infotm/imapx800/modules/uftl.ko:root/sbin/modules/uftl.ko 
	
#emuinit
PRODUCT_COPY_FILES += \
    device/infotm/imapx800/bin/emuinit:root/sbin/emuinit \

#mkimg
PRODUCT_COPY_FILES += \
    device/infotm/imapx800/bin/busybox:system/bin/busybox \
	device/infotm/imapx800/bin/mkimage:system/bin/mkimage \
	device/infotm/imapx800/bin/mkyaffs2image:system/bin/mkyaffs2image \
	device/infotm/imapx800/bin/mknandimage:system/bin/mknandimage \
	device/infotm/imapx800/bin/tar:system/bin/tar \
	device/infotm/imapx800/bin/mkinandimage:system/bin/mkinandimage \
	device/infotm/imapx800/bin/mkbootfs:system/bin/mkbootfs \
	device/infotm/imapx800/bin/installtool:system/bin/installtool

#preinstall
PRODUCT_COPY_FILES += \
	device/infotm/imapx800/bin/preinstall.sh:system/bin/preinstall.sh 
#tts
#PRODUCT_COPY_FILES += \
	device/infotm/imapx800/tts/lang_pico/en-GB_kh0_sg.bin:system/tts/lang_pico/en-GB_kh0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/en-US_lh0_sg.bin:system/tts/lang_pico/en-US_lh0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/de-DE_gl0_sg.bin:system/tts/lang_pico/de-DE_gl0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/fr-FR_nk0_sg.bin:system/tts/lang_pico/fr-FR_nk0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/it-IT_cm0_sg.bin:system/tts/lang_pico/it-IT_cm0_sg.bin \
	device/infotm/imapx800/tts/lang_pico/en-GB_ta.bin:system/tts/lang_pico/en-GB_ta.bin \
	device/infotm/imapx800/tts/lang_pico/en-US_ta.bin:system/tts/lang_pico/en-US_ta.bin \
	device/infotm/imapx800/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin \
	device/infotm/imapx800/tts/lang_pico/de-DE_ta.bin:system/tts/lang_pico/de-DE_ta.bin \
	device/infotm/imapx800/tts/lang_pico/fr-FR_ta.bin:system/tts/lang_pico/fr-FR_ta.bin \
	device/infotm/imapx800/tts/lang_pico/it-IT_ta.bin:system/tts/lang_pico/it-IT_ta.bin 

#google apps lib
PRODUCT_COPY_FILES += \
	device/infotm/imapx800/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
	device/infotm/imapx800/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    device/infotm/imapx800/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
	device/infotm/imapx800/lib/libspeexresampler.so:system/lib/libspeexresampler.so

# These are the Infotm Media configuration files
PRODUCT_COPY_FILES += \
	frameworks/av/media/libstagefright/infotm/omx/omx_core/Infotmomxregistry:system/etc/Infotmomxregistry \
	device/infotm/imapx800/etc/media_codecs.xml:system/etc/media_codecs.xml
#	device/infotm/imapx800/etc/media_profiles.xml:system/etc/media_profiles.xml \

src_files:=$(shell ls device/infotm/imapx800/etc/mediaProfile)
PRODUCT_COPY_FILES += $(foreach file, $(src_files),\
					  device/infotm/imapx800/etc/mediaProfile/$(file):system/etc/mediaProfile/$(file)) 


# These are the OpenMAX IL modules
PRODUCT_PACKAGES += \
	libIM_OMX_Core \
	libOMX.Infotm.Video.Decoder \

#system app
PRODUCT_PACKAGES += \
	SoundRecorder \
	#LegacyCamera \

#HDMI
PRODUCT_PACKAGES += \
	HDMISettings

# Misc other modules
PRODUCT_PACKAGES += \
	lights.default \
	sensors.default \
    	sensorcontrol.default  \
	libsensorcontrol


# Camera
PRODUCT_PACKAGES += \
	camera.default

#hw ui
PRODUCT_PACKAGES += \
	libhwui
# audio
PRODUCT_PACKAGES += \
	audio_policy.imapx800 \
	audio.primary.imapx800 \
	alsa.default \
	acoustics.default

#Live WallPapers
#PRODUCT_PACKAGES += \
	LiveWallpapers \
	LiveWallpapersPicker \
	PhaseBean \
	NoiseField \
	VisualizationWallpapers \
	HoloSpiralWallpaper \
	Galaxy4 \
	MagicSmokeWallpapers \

#item
PRODUCT_PACKAGES += \
	libBoardItems

#BeltController
PRODUCT_PACKAGES +=	\
	libBeltController

#charger
PRODUCT_PACKAGES += \
	charger \
	charger_res_images \

#ntfs
PRODUCT_PACKAGES += \
	ntfs-3g

#mkimage
PRODUCT_PACKAGES += \
	mkimage

#gpu
PRODUCT_PACKAGES += \
	libEGL_mali \
	libGLESv1_CM_mali \
	libGLESv2_mali

PRODUCT_COPY_FILES += \

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libstagefrighthw  	\
	libHDMIHelper

PRODUCT_PACKAGES += \
	stapd_cli \
	wpa_cli \
	wpa_supplicant \
	lib_driver_cmd_rtl \
	wpa_supplicant.conf \
	libiw \
	iwconfig \
	iwlist \
	iwpriv \
	sh \
	dhcpcd.conf \
	libext4_utils \
	infoibu \
	make_ext4fs

PRODUCT_CHARACTERISTICS := tablet
