PRODUCT_PACKAGES += \
    lib8270enc \
    libEGL_mali \
    libGLESv1_CM_mali \
    libGLESv2_mali \
    libInfotmMediaAudioDec \
    libInfotmMediaBlt \
    libInfotmMediaBuffalloc \
    libInfotmMediaCamera \
    libInfotmMediaCameralib_isp \
    libInfotmMediaCameralib_stub \
    libInfotmMediaCameralib_usb \
    libInfotmMediaCameralib_camif \
    libInfotmMediaDBT \
    libInfotmMediaG2D \
    libInfotmMediaIDS \
    libInfotmMediaIPC \
    libInfotmMediaImage \
    libInfotmMediaJpegDec \
    libInfotmMediaJpegenc \
    libInfotmMediaParser \
    libInfotmMediaParserlib \
    libInfotmMediaRefptr \
    libInfotmMediaUtlzstatc \
    libInfotmMediaVideoDec \
    libInfotmMediaVideoDec2 \
    libInfotmMediaVideoEnc \
    libMali \
    libUMP \
    libim_avcodec \
    libim_avformat \
    libim_avutil \
    libg1dec_avs \
    libg1dec_dwl \
    libg1dec_h264 \
    libg1dec_jpeg \
    libg1dec_mpeg2 \
    libg1dec_mpeg4 \
    libg1dec_pp \
    libg1dec_rv \
    libg1dec_vc1 \
    libg1dec_vp6 \
    libg1dec_vp8 \
    libim_swresample \
    libim_swscale \
