/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_VideoPlayer_hdmi_ServiceHDMI */

#include "InfotmMedia.h"
#include "IM_idsapi.h"  



#ifdef __cplusplus
extern "C" {
#endif

#if 1
 #define INFOMSG(str, ...) ALOGE(str, ##__VA_ARGS__)
#else
 #define INFOMSG(str, ...)
#endif

JavaVM* gVM = IM_NULL;
jobject thiz_g;
static jmethodID notifyInfo;

IDSEXINST gExtHandle = IM_NULL;

static void extlayer_callback(IM_UINT32 evt, void *p)
{
	INFOMSG(" extlayer_callback , evt=0x%x  \n",evt);

	if(gVM == IM_NULL) {
		INFOMSG("No JavaVM, no callback!\n");
		return;
	}

	JNIEnv* env = IM_NULL;                                              
	if(gVM->GetEnv((void**) &env, JNI_VERSION_1_4) != JNI_OK) {
		if(gVM->AttachCurrentThread(&env, NULL) != JNI_OK) {
			ALOGE("Attch current thread to JVM failed!\n");
            return;
        }

        switch (evt){
            case IDS_EXTLAYER_EVENT_BACK_TO_LOCAL:
            case IDS_EXTLAYER_EVENT_EXTDEV_BREAK:
                env->CallVoidMethod(thiz_g, notifyInfo, 1);
                break;
            default :
                INFOMSG(" evt not recognized. %d   \n",evt);
                break;
        }
        gVM->DetachCurrentThread();
    }
    INFOMSG("###  %s - end - %d \n",__func__,__LINE__);
}


/*
 * Class:     com_android_VideoPlayer_hdmi_HDMIHelper
 * Method:    registerExtlayerUse
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_com_android_VideoPlayer_hdmi_ServiceHDMI_registerExtlayerUse
// (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_com_android_VideoPlayer_hdmi_HDMIHelper_registerExtlayerUse
(JNIEnv *env, jobject thiz)
{
	IM_RET ret;

	INFOMSG(" %s  -enter- %d  -\n",__func__,__LINE__);

	env->GetJavaVM(&gVM);
	thiz_g = env->NewGlobalRef(thiz);
	jclass clazz = env->GetObjectClass(thiz);
	notifyInfo = env->GetMethodID(clazz, "notify", "(I)V");

	ret = ids_wlayer_register_extend_use(&gExtHandle,(extlayer_use_listener_t)extlayer_callback);
	if (ret != IM_RET_OK){
		ALOGE(" ids_wlayer_register_extend_use failed \n");
		return -1;
	}

	INFOMSG("### %s  -end - %d  -\n",__func__,__LINE__);
	return 0;
}

/*
 * Class:     com_android_VideoPlayer_hdmi_HDMIHelper
 * Method:    unregisterExtlayerUse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_android_VideoPlayer_hdmi_HDMIHelper_unregisterExtlayerUse
  (JNIEnv *env, jobject thiz)
{
	INFOMSG("%s -enter - %d  -\n",__func__,__LINE__);
	if (gExtHandle != IM_NULL){
		ids_wlayer_unregister_extend_use(gExtHandle);
		gExtHandle = IM_NULL;
	}
	INFOMSG("### %s - end  %d  -\n",__func__,__LINE__);
	return 0;
}

#ifdef __cplusplus
}
#endif
